modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "arbitrarydelight"
version = "${version}"
displayName = "Arbitrary Delight"
authors = "Ri0t"
description = '''
A Farmer's Delight Add-on that adds Arbitrary Additions :)
'''
logoFile = "arbitrarydelight_logo"

[[dependencies.arbitrarydelight]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arbitrarydelight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arbitrarydelight]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
