modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="arbitrarydelight"
version="1.0.0"
displayName="Arbitrary Delight"
authors="Ri0t"
logoFile="assets/arbitrarydelight/arbitrarydelight_logo.png"
description='''
A Farmer's Delight Add-on that adds Arbitrary Additions :)
'''

[[dependencies.arbitrarydelight]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.arbitrarydelight]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.arbitrarydelight]]
modId="farmersdelight"
mandatory=true
versionRange="[1.20.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.arbitrarydelight]]
modId="jei"
mandatory=false
versionRange="[1.20.1,)"
ordering="AFTER"
side="BOTH"
