modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="arbitrarydelight"
version="1.0.0"
displayName="Arbitrary Delight"
authors="Ri0t"
logoFile="assets/arbitrarydelight/arbitrarydelight_logo.png"
description='''
A Farmer's Delight Add-on that adds Arbitrary Additions :)
'''

[[dependencies.arbitrarydelight]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.arbitrarydelight]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.arbitrarydelight]]
modId="farmersdelight"
type="required"
versionRange="[1.2.9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.arbitrarydelight]]
modId="jei"
type="optional"
versionRange="[19.21.1.300,)"
ordering="AFTER"
side="BOTH"
