modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "arbitrarydelight"
version = "${version}"
displayName = "Arbitrary Delight"
authors = "Ri0t"
description = '''
A Farmer's Delight Add-on that adds Arbitrary Additions :)
'''
#logoFile="assets/arbitrarydelight/arbitrarydelight_logo.png"

[[dependencies.arbitrarydelight]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arbitrarydelight]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arbitrarydelight]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "arbitrarydelight.mixins.json"
